# action.yml
name: 'Liquibase Github Action'
description: 'Validate, Prepare and Execute Liquibase CLI'
inputs:
  operation: # [update, updateCount, tag, updateToTag, rollback, rollbackCount, rollbackToDate, updateSQL, futureRollbackSQL, status, history, diff, checks run]
    description: 'Operation to run'
    required: true
  classpath: # string
    description: 'Path to Change Log directory'
    required: false
  changeLogFile: # string
    description: 'Name of Change Log File'
    required: false
  username: # string
    description: 'Database Username'
    required: false
  password: # string
    description: 'Database Password'
    required: false
  url: # string
    description: 'Database URL'
    required: false
  count: # integer
    description: 'Count for updateCount and rollbackCount'
    required: false
  tag: # string
    description: 'Tag for tag, updateToTag, and rollback'
    required: false
  date: # string
    description: 'Date for rollbackToDate'
    required: false
  referenceUrl: # string
    description: 'Reference URL for diff'
    required: false
  checksSettingsFile: # string
    description: 'Configuration file for checks execution'
    required: false
  proLicenseKey: # string
    description: 'DEPRECATED: Liquibase Pro license key used to unlock paid capabilities'
    required: false
  hubApiKey: # string
    description: 'Liquibase Hub API key for operations'
    required: false
  licenseKey: # string
    description: 'Liquibase license key used to unlock paid capabilities'
    required: false
  databaseChangeLogTableName: # string
    description: 'Specifies the Liquibase changelog table'
    required: false
  databaseChangeLogLockTableName: # string
    description: 'Specifies the Liquibase changelog lock table'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
#   args:
#     - ${{ inputs.operation }}
#     - ${{ inputs.classpath }}
#     - ${{ inputs.changeLogFile }}
#     - ${{ inputs.username }}
#     - ${{ inputs.password }}
#     - ${{ inputs.url }}
#     - ${{ inputs.count }}
#     - ${{ inputs.tag }}
#     - ${{ inputs.date }}
#     - ${{ inputs.referenceUrl }}
#     - ${{ inputs.checksSettingsFile }}
#     - ${{ inputs.proLicenseKey }}
#     - ${{ inputs.hubApiKey }}
#     - ${{ inputs.licenseKey }}
#     - ${{ inputs.databaseChangeLogTableName }}
#     - ${{ inputs.databaseChangeLogLockTableName }}
# branding:
#   icon: database
#   color: red
